events {}
http {
  server {
    listen 8443 ssl;
    server_name identity.localhost;
    ssl_certificate /tls/demo.crt;
    ssl_certificate_key /tls/demo.key;
    location / {
      proxy_pass http://keycloak:8080;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port 8443;
    }
  }
  server {
    listen 8443 ssl;
    server_name zephyr.localhost;
    ssl_certificate /tls/demo.crt;
    ssl_certificate_key /tls/demo.key;
    location = /metrics { return 404; }
    location / {
      resolver 127.0.0.11 valid=5s;
      set $platform http://server:8080;
      proxy_pass $platform;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_read_timeout 120s;
    }
  }
  server {
    listen 8443 ssl;
    server_name checkout.localhost;
    ssl_certificate /tls/demo.crt;
    ssl_certificate_key /tls/demo.key;
    location / {
      resolver 127.0.0.11 valid=5s;
      set $application http://checkout-app:8090;
      proxy_pass $application;
      proxy_set_header Host $http_host;
    }
  }
}
